FROM golang:1.25.5-alpine AS builder

WORKDIR /app

COPY go.mod ./

RUN go mod download

COPY . .

# Build the Worker binary
# CGO_ENABLED=0 creates a statically linked binary (no dependency on system libc)
# -o worker-bin names the output file
RUN CGO_ENABLED=0 GOOS=linux go build -o worker-bin cmd/worker/main.go


FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/worker-bin .

EXPOSE 8080

CMD ["./worker-bin"]